approvedGitRepositories:
  - "ssh://git@github.com/user-komeda/*"

enableScripts: false

npmMinimalAgeGate: 3d

npmPreapprovedPackages: []

checksumBehavior: throw

enableStrictSsl: true

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.15.0.cjs