// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/health": {
    params: {};
  };
  "/videos": {
    params: {};
  };
  "/videos/:id": {
    params: {
      "id": string;
    };
  };
  "/upload": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/health" | "/videos" | "/videos/:id" | "/upload";
  };
  "routes/home/route.tsx": {
    id: "routes/home/route";
    page: "/";
  };
  "routes/health.ts": {
    id: "routes/health";
    page: "/health";
  };
  "routes/video/route.tsx": {
    id: "routes/video/route";
    page: "/videos";
  };
  "routes/video/[id]/route.tsx": {
    id: "routes/video/[id]/route";
    page: "/videos/:id";
  };
  "layout/upload/layout.tsx": {
    id: "layout/upload/layout";
    page: "/upload";
  };
  "routes/upload/route.tsx": {
    id: "routes/upload/route";
    page: "/upload";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home/route": typeof import("./app/routes/home/route.tsx");
  "routes/health": typeof import("./app/routes/health.ts");
  "routes/video/route": typeof import("./app/routes/video/route.tsx");
  "routes/video/[id]/route": typeof import("./app/routes/video/[id]/route.tsx");
  "layout/upload/layout": typeof import("./app/layout/upload/layout.tsx");
  "routes/upload/route": typeof import("./app/routes/upload/route.tsx");
};