// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/upload": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/upload";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "../src/feature/upload/layout.tsx": {
    id: "../src/feature/upload/layout";
    page: "/upload";
  };
  "routes/upload.tsx": {
    id: "routes/upload";
    page: "/upload";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "../src/feature/upload/layout": unknown;
  "routes/upload": typeof import("./app/routes/upload.tsx");
};