name: Docker Image Cd

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  LOCAL_INFISICAL_CLIENT_ID: ${{ secrets.LOCAL_INFISICAL_CLIENT_ID }}
  LOCAL_INFISICAL_CLIENT_SECRET: ${{ secrets.LOCAL_INFISICAL_CLIENT_SECRET }}
  LOCAL_INFISICAL_PROJECT_ID: ${{ secrets.LOCAL_INFISICAL_PROJECT_ID }}

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: webfactory/ssh-agent@v0.10.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - uses: actions/checkout@v7

      - name: "docker buildxが使えるようにする"
        uses: docker/setup-buildx-action@v4

      - name: "ghcr.ioにログインする"
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "メタデータを作成する"
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-frontend
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=sha

      - name: "コンテナイメージをビルドしてghcr.ioにコンテナイメージをpushする"
        uses: docker/build-push-action@v7
        with:
          file: ./apps/frontend/Dockerfile
          push: true
          ssh: default
          secrets: |
            infisical_client_id=${{ secrets.LOCAL_INFISICAL_CLIENT_ID }}
            infisical_client_secret=${{ secrets.LOCAL_INFISICAL_CLIENT_SECRET }}
            infisical_project_id=${{ secrets.LOCAL_INFISICAL_PROJECT_ID }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: webfactory/ssh-agent@v0.10.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - uses: actions/checkout@v7

      - name: "docker buildxが使えるようにする"
        uses: docker/setup-buildx-action@v4

      - name: "ghcr.ioにログインする"
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "メタデータを作成する"
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-backend
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=sha

      - name: "コンテナイメージをビルドしてghcr.ioにコンテナイメージをpushする"
        uses: docker/build-push-action@v7
        with:
          file: ./apps/backend/Dockerfile
          push: true
          ssh: default
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
