name: Docker Image Cd

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - name: "docker buildxが使えるようにする"
        uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4
      - name: "ghcr.ioにログインする"
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: "メタデータを作成する"
        id: meta # 後段で参照できるようにoutputsに登録する
        uses: docker/metadata-action@80c7e94dd9b9319bd5eb7a0e0fe9291e23a2a2e9 # v6
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-frontend
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=sha
          labels: |
            org.opencontainers.image.title=sample-app
            org.opencontainers.image.vendor="AP Communications Co.,Ltd."
            org.opencontainers.image.licenses=Apache-2.0
      - name: "コンテナイメージをビルドしてghcr.ioにコンテナイメージをpushする"
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7
        with:
          file: ./apps/frontend/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }} # 前ステップで設定したタグを参照する
          labels: ${{ steps.meta.outputs.labels }} # 前ステップで設定したラベルを参照する
  build-backend:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - name: "docker buildxが使えるようにする"
        uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4
      - name: "ghcr.ioにログインする"
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: "メタデータを作成する"
        id: meta # 後段で参照できるようにoutputsに登録する
        uses: docker/metadata-action@80c7e94dd9b9319bd5eb7a0e0fe9291e23a2a2e9 # v6
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-backend
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=sha
          labels: |
            org.opencontainers.image.title=sample-app
            org.opencontainers.image.vendor="AP Communications Co.,Ltd."
            org.opencontainers.image.licenses=Apache-2.0
      - name: "コンテナイメージをビルドしてghcr.ioにコンテナイメージをpushする"
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7
        with:
          file: ./apps/backend/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }} # 前ステップで設定したタグを参照する
          labels: ${{ steps.meta.outputs.labels }} # 前ステップで設定したラベルを参照する

